[2025-08-10 06:55:12 +0000] [1374026] [INFO] Starting gunicorn 23.0.0
[2025-08-10 06:55:12 +0000] [1374026] [INFO] Listening at: http://0.0.0.0:8000 (1374026)
[2025-08-10 06:55:12 +0000] [1374026] [INFO] Using worker: sync
[2025-08-10 06:55:12 +0000] [1374027] [INFO] Booting worker with pid: 1374027
[2025-08-10 06:55:12 +0000] [1374028] [INFO] Booting worker with pid: 1374028
[2025-08-10 06:55:12 +0000] [1374029] [INFO] Booting worker with pid: 1374029
[2025-08-10 06:55:12 +0000] [1374030] [INFO] Booting worker with pid: 1374030
[2025-08-10 06:55:12 +0000] [1374031] [INFO] Booting worker with pid: 1374031
[2025-08-10 06:55:12 +0000] [1374035] [INFO] Booting worker with pid: 1374035
[2025-08-10 06:55:12 +0000] [1374034] [INFO] Starting gunicorn 23.0.0
[2025-08-10 06:55:13 +0000] [1374034] [INFO] Listening at: http://0.0.0.0:8001 (1374034)
[2025-08-10 06:55:13 +0000] [1374034] [INFO] Using worker: sync
[2025-08-10 06:55:13 +0000] [1374036] [INFO] Booting worker with pid: 1374036
[2025-08-10 06:55:13 +0000] [1374037] [INFO] Booting worker with pid: 1374037
[2025-08-10 06:55:13 +0000] [1374038] [INFO] Booting worker with pid: 1374038
[2025-08-10 06:55:13 +0000] [1374039] [INFO] Booting worker with pid: 1374039
[2025-08-10 06:55:13 +0000] [1374040] [INFO] Booting worker with pid: 1374040
[2025-08-10 06:55:13 +0000] [1374041] [INFO] Booting worker with pid: 1374041
[2025-08-10 06:55:13 +0000] [1374042] [INFO] Booting worker with pid: 1374042
[2025-08-10 06:55:13 +0000] [1374043] [INFO] Booting worker with pid: 1374043
[2025-08-10 06:55:13 +0000] [1374044] [INFO] Booting worker with pid: 1374044
[2025-08-10 06:55:13 +0000] [1374045] [INFO] Booting worker with pid: 1374045
[2025-08-10 06:55:13 +0000] [1374048] [INFO] Starting gunicorn 23.0.0
[2025-08-10 06:55:13 +0000] [1374048] [INFO] Listening at: http://0.0.0.0:8002 (1374048)
[2025-08-10 06:55:13 +0000] [1374048] [INFO] Using worker: sync
[2025-08-10 06:55:13 +0000] [1374049] [INFO] Booting worker with pid: 1374049
[2025-08-10 06:55:14 +0000] [1374050] [INFO] Booting worker with pid: 1374050
[2025-08-10 06:55:14 +0000] [1374052] [INFO] Booting worker with pid: 1374052
[2025-08-10 06:55:14 +0000] [1374051] [INFO] Booting worker with pid: 1374051
[2025-08-10 06:55:14 +0000] [1374053] [INFO] Booting worker with pid: 1374053
[2025-08-10 06:55:14 +0000] [1374054] [INFO] Booting worker with pid: 1374054
[2025-08-10 06:55:14 +0000] [1374056] [INFO] Booting worker with pid: 1374056
[2025-08-10 06:55:14 +0000] [1374055] [INFO] Booting worker with pid: 1374055
2025-08-10 06:55:29,010 - libs.lib__config - INFO - .env chargé depuis: /home/michel/brightnessaiv3/.env
2025-08-10 06:55:30,260 - libs.lib__config - INFO - .env chargé depuis: /home/michel/brightnessaiv3/.env
2025-08-10 06:55:30,324 - libs.lib__config - INFO - .env chargé depuis: /home/michel/brightnessaiv3/.env
2025-08-10 06:55:30,442 - libs.lib__config - INFO - .env chargé depuis: /home/michel/brightnessaiv3/.env
2025-08-10 06:55:30,626 - libs.lib__config - INFO - .env chargé depuis: /home/michel/brightnessaiv3/.env
2025-08-10 06:55:30,866 - libs.lib__config - INFO - .env chargé depuis: /home/michel/brightnessaiv3/.env
2025-08-10 06:55:31,120 - libs.lib__config - INFO - .env chargé depuis: /home/michel/brightnessaiv3/.env
2025-08-10 06:55:31,271 - libs.lib__config - INFO - .env chargé depuis: /home/michel/brightnessaiv3/.env
[2025-08-10 06:55:38 +0000] [1374036] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/michel/brightnessaiv3/api/transformers_api.py", line 10, in <module>
    from libs.lib__transformers import searchembedding
  File "/home/michel/brightnessaiv3/libs/lib__transformers.py", line 35, in <module>
    from moviepy.editor import *
ModuleNotFoundError: No module named 'moviepy.editor'
[2025-08-10 06:55:38 +0000] [1374036] [INFO] Worker exiting (pid: 1374036)
[2025-08-10 06:55:39 +0000] [1374043] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/michel/brightnessaiv3/api/transformers_api.py", line 10, in <module>
    from libs.lib__transformers import searchembedding
  File "/home/michel/brightnessaiv3/libs/lib__transformers.py", line 35, in <module>
    from moviepy.editor import *
ModuleNotFoundError: No module named 'moviepy.editor'
[2025-08-10 06:55:39 +0000] [1374043] [INFO] Worker exiting (pid: 1374043)
[2025-08-10 06:55:39 +0000] [1374040] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/michel/brightnessaiv3/api/transformers_api.py", line 10, in <module>
    from libs.lib__transformers import searchembedding
  File "/home/michel/brightnessaiv3/libs/lib__transformers.py", line 35, in <module>
    from moviepy.editor import *
ModuleNotFoundError: No module named 'moviepy.editor'
[2025-08-10 06:55:39 +0000] [1374040] [INFO] Worker exiting (pid: 1374040)
[2025-08-10 06:55:39 +0000] [1374042] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/michel/brightnessaiv3/api/transformers_api.py", line 10, in <module>
    from libs.lib__transformers import searchembedding
  File "/home/michel/brightnessaiv3/libs/lib__transformers.py", line 35, in <module>
    from moviepy.editor import *
ModuleNotFoundError: No module named 'moviepy.editor'
[2025-08-10 06:55:39 +0000] [1374042] [INFO] Worker exiting (pid: 1374042)
[2025-08-10 06:55:39 +0000] [1374041] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/michel/brightnessaiv3/api/transformers_api.py", line 10, in <module>
    from libs.lib__transformers import searchembedding
  File "/home/michel/brightnessaiv3/libs/lib__transformers.py", line 35, in <module>
    from moviepy.editor import *
ModuleNotFoundError: No module named 'moviepy.editor'
[2025-08-10 06:55:39 +0000] [1374041] [INFO] Worker exiting (pid: 1374041)
[2025-08-10 06:55:39 +0000] [1374039] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/michel/brightnessaiv3/api/transformers_api.py", line 10, in <module>
    from libs.lib__transformers import searchembedding
  File "/home/michel/brightnessaiv3/libs/lib__transformers.py", line 35, in <module>
    from moviepy.editor import *
ModuleNotFoundError: No module named 'moviepy.editor'
[2025-08-10 06:55:39 +0000] [1374039] [INFO] Worker exiting (pid: 1374039)
[2025-08-10 06:55:39 +0000] [1374044] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/michel/brightnessaiv3/api/transformers_api.py", line 10, in <module>
    from libs.lib__transformers import searchembedding
  File "/home/michel/brightnessaiv3/libs/lib__transformers.py", line 35, in <module>
    from moviepy.editor import *
ModuleNotFoundError: No module named 'moviepy.editor'
[2025-08-10 06:55:39 +0000] [1374044] [INFO] Worker exiting (pid: 1374044)
[2025-08-10 06:55:39 +0000] [1374045] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/michel/brightnessaiv3/api/transformers_api.py", line 10, in <module>
    from libs.lib__transformers import searchembedding
  File "/home/michel/brightnessaiv3/libs/lib__transformers.py", line 35, in <module>
    from moviepy.editor import *
ModuleNotFoundError: No module named 'moviepy.editor'
[2025-08-10 06:55:39 +0000] [1374045] [INFO] Worker exiting (pid: 1374045)
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
[2025-08-10 06:55:42 +0000] [1374034] [ERROR] Worker (pid:1374036) exited with code 3
[2025-08-10 06:55:42 +0000] [1374034] [ERROR] Worker (pid:1374043) exited with code 3
Traceback (most recent call last):
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 208, in run
    self.sleep()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 359, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 241, in handle_chld
    self.reap_workers()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 529, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michel/myenv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 66, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/base.py", line 235, in run
    super().run()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/app/base.py", line 71, in run
    Arbiter(self).run()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 228, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 341, in halt
    self.stop()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 395, in stop
    time.sleep(0.1)
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 241, in handle_chld
    self.reap_workers()
  File "/home/michel/myenv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 529, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2025-08-10 06:55:46,781 - libs.lib__config - INFO - .env chargé depuis: /home/michel/brightnessaiv3/.env
2025-08-10 06:55:46,796 - libs.lib__config - INFO - .env chargé depuis: /home/michel/brightnessaiv3/.env
2025-08-10 06:55:46,828 - libs.lib__config - INFO - .env chargé depuis: /home/michel/brightnessaiv3/.env
2025-08-10 06:55:46,823 - libs.lib__config - INFO - .env chargé depuis: /home/michel/brightnessaiv3/.env
2025-08-10 06:55:46,858 - libs.lib__config - INFO - .env chargé depuis: /home/michel/brightnessaiv3/.env
2025-08-10 06:55:46,879 - libs.lib__config - INFO - .env chargé depuis: /home/michel/brightnessaiv3/.env
2025-08-10 06:55:46,906 - libs.lib__config - INFO - .env chargé depuis: /home/michel/brightnessaiv3/.env
2025-08-10 06:55:46,981 - libs.lib__config - INFO - .env chargé depuis: /home/michel/brightnessaiv3/.env
